export const APP_NAME = 'Drinkly'
export const APP_TAGLINE = 'Order Responsibly. Delivered Legally.'
export const DEFAULT_CURRENCY = 'USD'

export const FREE_DELIVERY_THRESHOLD = 50.0
export const PLATFORM_FEE_PERCENTAGE = 5

export const PAGINATION_DEFAULTS = {
  page: 1,
  limit: 20,
  maxLimit: 100,
} as const

export const ROLES = {
  CUSTOMER: 'CUSTOMER',
  RETAILER_OWNER: 'RETAILER_OWNER',
  RETAILER_STAFF: 'RETAILER_STAFF',
  DELIVERY_AGENT: 'DELIVERY_AGENT',
  COMPLIANCE_OFFICER: 'COMPLIANCE_OFFICER',
  ADMIN: 'ADMIN',
  SUPER_ADMIN: 'SUPER_ADMIN',
} as const

export type Role = keyof typeof ROLES

export const ORDER_STATUSES = {
  CREATED: 'CREATED',
  PAYMENT_PENDING: 'PAYMENT_PENDING',
  PAID: 'PAID',
  COMPLIANCE_CHECK: 'COMPLIANCE_CHECK',
  RETAILER_ACCEPTED: 'RETAILER_ACCEPTED',
  PREPARING: 'PREPARING',
  READY_FOR_PICKUP: 'READY_FOR_PICKUP',
  DELIVERY_ASSIGNED: 'DELIVERY_ASSIGNED',
  PICKED_UP: 'PICKED_UP',
  OUT_FOR_DELIVERY: 'OUT_FOR_DELIVERY',
  DELIVERY_VERIFICATION: 'DELIVERY_VERIFICATION',
  DELIVERED: 'DELIVERED',
  CANCELLED: 'CANCELLED',
  REJECTED: 'REJECTED',
  REFUNDED: 'REFUNDED',
  FAILED: 'FAILED',
} as const

export type OrderStatus = keyof typeof ORDER_STATUSES

export const PRODUCT_STATUSES = {
  ACTIVE: 'ACTIVE',
  OUT_OF_STOCK: 'OUT_OF_STOCK',
  HIDDEN: 'HIDDEN',
  SUSPENDED: 'SUSPENDED',
  PROHIBITED: 'PROHIBITED',
} as const

export type ProductStatus = keyof typeof PRODUCT_STATUSES

export const RETAILER_STATUSES = {
  PENDING: 'PENDING',
  DOCUMENT_REVIEW: 'DOCUMENT_REVIEW',
  VERIFIED: 'VERIFIED',
  ACTIVE: 'ACTIVE',
  SUSPENDED: 'SUSPENDED',
  EXPIRED: 'EXPIRED',
  REJECTED: 'REJECTED',
} as const

export type RetailerStatus = keyof typeof RETAILER_STATUSES

export const DELIVERY_STATUSES = {
  ASSIGNED: 'ASSIGNED',
  ACCEPTED: 'ACCEPTED',
  PICKED_UP: 'PICKED_UP',
  IN_TRANSIT: 'IN_TRANSIT',
  DELIVERED: 'DELIVERED',
  FAILED: 'FAILED',
} as const

export type DeliveryStatus = keyof typeof DELIVERY_STATUSES

export const PAYMENT_STATUSES = {
  INITIATED: 'INITIATED',
  PENDING: 'PENDING',
  AUTHORIZED: 'AUTHORIZED',
  SUCCESS: 'SUCCESS',
  FAILED: 'FAILED',
  REFUND_PENDING: 'REFUND_PENDING',
  REFUNDED: 'REFUNDED',
} as const

export type PaymentStatus = keyof typeof PAYMENT_STATUSES

export const AGE_VERIFICATION_STATUSES = {
  PENDING: 'PENDING',
  VERIFIED: 'VERIFIED',
  FAILED: 'FAILED',
  EXPIRED: 'EXPIRED',
  REVIEW_REQUIRED: 'REVIEW_REQUIRED',
  BLOCKED: 'BLOCKED',
} as const

export type AgeVerificationStatus = keyof typeof AGE_VERIFICATION_STATUSES

export const NOTIFICATION_TYPES = {
  ORDER_UPDATE: 'ORDER_UPDATE',
  DELIVERY_UPDATE: 'DELIVERY_UPDATE',
  PAYMENT_UPDATE: 'PAYMENT_UPDATE',
  PROMOTION: 'PROMOTION',
  SYSTEM: 'SYSTEM',
  COMPLIANCE: 'COMPLIANCE',
  VERIFICATION: 'VERIFICATION',
  SUPPORT: 'SUPPORT',
} as const

export type NotificationType = keyof typeof NOTIFICATION_TYPES

export const SUPPORT_CATEGORIES = {
  ORDER_ISSUE: 'ORDER_ISSUE',
  DELIVERY_ISSUE: 'DELIVERY_ISSUE',
  PAYMENT_ISSUE: 'PAYMENT_ISSUE',
  ACCOUNT_ISSUE: 'ACCOUNT_ISSUE',
  AGE_VERIFICATION: 'AGE_VERIFICATION',
  PRODUCT_INQUIRY: 'PRODUCT_INQUIRY',
  RETAILER_INQUIRY: 'RETAILER_INQUIRY',
  COMPLIANCE: 'COMPLIANCE',
  FEEDBACK: 'FEEDBACK',
  OTHER: 'OTHER',
} as const

export type SupportCategory = keyof typeof SUPPORT_CATEGORIES
